version: '3.8'

services:
  api:
    build:
      context: .           
      dockerfile: Dockerfile
    ports:
      - "5086:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=TravelAgencyDB;User=root;Password=my-secret-pw;
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: TravelAgencyDB
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
